# Generated by Django 4.1.5 on 2023-02-15 09:56

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, validators=[user.validators.validate_first_name], verbose_name='სახელი'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, validators=[user.validators.validate_last_name], verbose_name='გვარი'),
        ),
    ]
