# Generated by Django 4.1.5 on 2023-02-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'პროცესშია'), (1, 'მიღებულია')], default=0, verbose_name='სტატუსი'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'ნაღდი ფული'), (1, 'ბარათით'), (2, 'სხვა')], default=1, verbose_name='გადახდის მეთოდი'),
        ),
    ]
